#language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx
  - rbx-19mode
  - ree
  - ruby-head

env:
  - JRUBY_OPTS="-Xcext.enabled=true"

script:
  - gem build ox.gemspec
  - gem install ox-*
