rvm:
  - 1.8.7
  - 1.9.1
  - 1.9.2
  - jruby
  - rbx
  - rbx-2.0
  - ree

script:
  - gem build ox.gemspec
  - gem install ox-*
  - ruby -I lib -I ext test/func.rb
  - ruby -I lib -I ext test/sax_test.rb
