os:
  - linux
  - osx

language: ruby

rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5

install: gem install test-unit

before_script:
  - gem build ox.gemspec
  - gem install ox-*
  - cd ext/ox
  - ruby extconf.rb && make clean all
  - cd ../..

script:
  - ./test/tests.rb
  - ./test/sax/sax_test.rb
