os:
  - linux
  - osx

sudo: false
env:
  global:
    - MAKE="make -j 2"

language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0

matrix:
  fast_finish: true
  exclude:
    - os: osx
      rvm: 2.3.8
    - os: osx
      rvm: 2.4.9
    - os: osx
      rvm: 2.5.7
    - os: osx
      rvm: 2.6.5
